#!/usr/bin/env bash

sourceFilePath="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# Local names are (currently) in format that is the same as names but changes 
# dots (.) for underscore dashes (_). Example: github_com_gardener_gardener
# Note: This is convetion and not normative
DEPENDENCY_UPGRADE_FILE=dep-upgrade-${LOCAL_DEPENDENCY_NAME}

# write dependency's updated version upon dependency upgrade notification in $DEPENDENCY_UPGRADE_FILE
echo ${DEPENDENCY_VERSION} > $sourceFilePath/../${DEPENDENCY_UPGRADE_FILE}
echo "${DEPENDENCY_VERSION} version set to $(cat $sourceFilePath/../${DEPENDENCY_UPGRADE_FILE})"
exit 0